- name: install  catalogue component
  hosts: mongodb
  become: yes
  tasks: 
  - name: setup npm resourses
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  - name: install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: out 
    ignore_errors: true

  - when: out.rc != 0
    name: create user roboshop
    ansible.builtin.user:
     name: roboshop

  - name: print the directory stats
    ansible.builtin.debug:
     msg: "output: {{directory}}"
  - when: directory.stat.exists == false